/*!
 * -------------------------------------------
 * Copyright (c) 2019, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     singleton.h
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2019-04-22
 * \Brief    implement of singleton.h
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */

#ifndef XPLUGINFLOW_INCLUDE_XPLUGINFLOW_UTILS_SINGLETON_H_
#define XPLUGINFLOW_INCLUDE_XPLUGINFLOW_UTILS_SINGLETON_H_
#include <assert.h>
namespace hobot {
template<typename T>
class CSingleton {
  struct object_creator {
   public:
    object_creator() {
      CSingleton<T>::Instance();
    }
    inline void do_nothing() const {
    }
  };

  static object_creator create_object;

 public:
  typedef T object_type;
  static object_type &Instance() {
    static object_type obj;
    // 据说这个do_nothing是确保create_object构造函数被调用
    // 这跟模板的编译有关
    create_object.do_nothing();
    return obj;
  }
};

template<typename T> typename CSingleton<T>::object_creator \
             CSingleton<T>::create_object;

}  // namespace hobot
#endif  // XPLUGINFLOW_INCLUDE_XPLUGINFLOW_UTILS_SINGLETON_H_
