/**
 * @file method_factory.cpp
 * @author your name (you@domain.com)
 * @brief DO NOT MODIFY THIS FILE, WHICH IS AUTO GENERATED BY COMPILER
 * @version 0.1
 * @date 2018-11-23
 *
 * @copyright Copyright (c) 2018
 *
 */

#include <string>
#include "hobotxroc/method_factory.h"
#include "FasterRCNNMethod/FasterRCNNMethod.h"
#include "MOTMethod/MOTMethod.h"
#include "FaceSnapFilterMethod/FaceSnapFilterMethod.h"
#include "GradingMethod/GradingMethod.h"
#include "SnapShotMethod/SnapShotMethod.h"
#include "CNNMethod/CNNMethod.h"

namespace HobotXRoc {
MethodPtr MethodFactory::CreateMethod(const std::string &method_name) {
  if ("FasterRCNNMethod" == method_name) {
    return MethodPtr(new FasterRCNNMethod());
  } else if ("MOTMethod" == method_name) {
    return MethodPtr(new MOTMethod());
  } else if ("CNNMethod" == method_name) {
    return MethodPtr(new CNNMethod());
  } else if ("FaceSnapFilterMethod" == method_name) {
    return MethodPtr(new FaceSnapFilterMethod());
  } else if ("GradingMethod" == method_name) {
    return MethodPtr(new GradingMethod());
  } else if ("SnapShotMethod" == method_name) {
    return MethodPtr(new SnapShotMethod());
  } else {
    return MethodPtr();
  }
}
}  // namespace HobotXRoc
