/*!
 * -------------------------------------------
 * Copyright (c) 2019, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     gtest_helper.h
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2019-04-15
 * \Brief    implement of gtest_helper.h
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
#ifndef PBTRANSFER_INCLUDE_PB_CP_SEND_COMMON_GTEST_HELPER_H_
#define PBTRANSFER_INCLUDE_PB_CP_SEND_COMMON_GTEST_HELPER_H_
#include <string>
#include <unordered_map>
extern std::unordered_map<std::string, std::string> CustomParams;
std::unordered_map<std::string, std::string> FilterOwnTestParam(int argc,
                                                                char **argv);
#endif  // PBTRANSFER_INCLUDE_PB_CP_SEND_COMMON_GTEST_HELPER_H_
