/*!
 * -------------------------------------------
 * Copyright (c) 2019, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     xplugin.cpp
 * \Author Songshan Gong
 * \Mail     songshan.gong@horizon.ai
 * \Version  1.0.0.0
 * \Date     2019-07-30
 * \Brief    implmentation of xplugin
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */

#include "xpluginflow/plugin/xplugin.h"
#include "xpluginflow/manager/msg_manager.h"
#include "xpluginflow/message/pluginflow/flowmsg.h"
namespace horizon {
namespace vision {
namespace xpluginflow {

void XPlugin::RegisterMsg(const std::string& type) {
  XMsgQueue::Instance().RegisterPlugin(shared_from_this(), type);
}


void XPlugin::UnRegisterMsg(const std::string& type) {
  // todo
  // 实现取消注册消息类型
}

void XPlugin::PushMsg(XPluginFlowMessagePtr msg) {
  XMsgQueue::Instance().PushMsg(msg);
}

}  // namespace xpluginflow
}  // namespace vision
}  // namespace horizon

